# The Problem

```{=html}
<!-- 
Outlining the issue / weak point / problem to be solved by this proposal. This should be a compelling section that sets the reader up for the next section - the proposed solution!

It is important to cover:

 - [ ] What the problem is
 - [ ] Who it affects
 - [ ] Have there been previous attempts to resolve the problem
 - [ ] Why it should be tackled
-->
```
```{=html}
<!-- 
Agregar: 

  Inraestructura técnica y social.

  Otras iniciativas.

  Apoyo de rOpenSci
  
  https://github.com/joelnitta/dovetail
-->
```
English is the de-facto international language and this is reflected in R by the use of English for function and argument names (e.g. `mean()` instead of `promedio()` or `Mittelwert()`) and documentation language.
And while contributed packages can be documented in other languages, the vast majority are documented in English.

There is [a small number of packages documented in other languages](https://cderv.rbind.io/2018/03/11/non-english-pkg-in-cran/), seemingly tailored to their target audience.
For example, the [labstatR](https://cran.r-project.org/web/packages/labstatR/index.html) package serves as a companion to the Italian book "Laboratorio Di Statistica Con R" and is documented in Italian.
Similarly, the [chilemapas](https://cran.r-project.org/web/packages/chilemapas/chilemapas.pdf) package provides simplified maps for Chile, with documentation and function names in Spanish.

Although these packages are more accessible for their intended users, they are much less accessible to the wider community.
Users who do not speak the language may find it difficult to discover and use the valuable functions and algorithms that these packages provide.
Package authors face the dilemma of either making their package inaccessible to their target demographic or isolating it from the wider R ecosystem.

The developer of the [utilsIPEA](https://cran.r-project.org/web/packages/utilsIPEA/index.html) package publicly expressed [the need for bilingual documentation](https://stackoverflow.com/questions/37288823/bilingual-english-and-portuguese-documentation-in-an-r-package), recognising that his package would be used by people in Brazil, who might prefer documentation in Portuguese, and the broader international community.

Interestingly, a few packages have tried to solve this dilemma by documenting their package in English and publishing a second version of the package documented in another language.
At least two packages on CRAN use this strategy: [ExpDes](https://cran.r-project.org/web/packages/ExpDes/index.html) and [ExpDes.pt](https://cran.r-project.org/web/packages/ExpDes.pt/index.html), as well as [orloca](https://cran.r-project.org/web/packages/orloca/index.html) and [orloca.es](https://cran.r-project.org/web/packages/orloca.es/index.html).

This approach is very hard to maintain, doesn't scale well to multiple languages, and requires users to load a different package to access the documentation in their language.
A more effective solution would be for R support for multilingual documentation as a standard feature.
