# The proposal

```{=html}
<!--
This is where the proposal should be outlined. 
-->
```
## Overview

```{=html}
<!--
At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.
-->
```
We propose to extend the R help system to enable multiple help pages for the same function in different languages by installing translation modules.
This was discussed at the R Project Sprint 2023 with R Core members Martin Mächler, Deepayan Sarcar and Michael Lawrence.
By default, `help()` would display the documentation in the user's preferred language, if available, and fall-back to the canonical documentation otherwise (most likely, in English).
It would also include a link to the canonical documentation and warnings if translations are not up to date.

## Detail

```{=html}
<!--
Go into more detail about the specifics of the project and it delivers against the problem.

Depending on project type the detail section should include:

 - [ ] Minimum Viable Product
 - [ ] Architecture
 - [ ] Assumptions
-->
```
The system would require three parts

### Translation of help pages

The translation of help pages would be performed using .pot files.
This would require a parser that takes .Rd files and creates .pot files ready for translation.
These files could be translated using existing infrastructure such as weblate.

### Installation of translation modules

The translated .po files would be hosted in translation modules.
These modules would piggyback on the package infrastructure but declare `PackageType: translation` and the name and version of the package they are translating in `Depends`.

Translation modules wouldn't necessarily maintained by the original package authors.
In principle, multiple translation modules for the same package and the same language could exist and the user can chose which version they install.
They could be hosted on CRAN or a CRAN-like repository.
Optionally, CRAN could develop quality checks on translation modules to ensure that they are up-to-date, such as a maximum percentage of missing strings or maximum percentage of fuzzy matches.

The user would install them like regular packages (e.g. `install.pacakges("mein.paket.en")`.
At installation the .Rd files of the original package would be parsed and translated using `gettext()` and the .po files in the translation module, and serialised into binary help pages (like regular packages have).

### Accessing documentation

The `help()` function would search for the loaded topics and if any translation is available, then it would use a new `language` argument to disambiguate.
This argument would default to `Sys.getenv("LANGUAGE")`.

Help pages would include a link to the original (canonical) documentation and add warnings if strings are untranslated/outdated.

### Minimum Viable Product

???
