# The Problem

```{=html}
<!-- 
Outlining the issue / weak point / problem to be solved by this proposal. This should be a compelling section that sets the reader up for the next section - the proposed solution!

It is important to cover:

 - [ ] What the problem is
 - [ ] Who it affects
 - [ ] Have there been previous attempts to resolve the problem
 - [ ] Why it should be tackled
-->
```
```{=html}
<!-- 
Agregar: 

  Inraestructura técnica y social.

  Otras iniciativas.

  Apoyo de rOpenSci
-->
```

R's help system is one of the great features of the language.
Usage, description and examples are available right there in the console.
It is important that this documentation is correct and useful both in the core packages and in the general contributed packages ecosystem.
To that aim, CRAN enforces a suite of policies on documentation, such as all exported object having documentation, all arguments being documented, etc.

Besides meeting those technical requirements, documentation needs to also be accessible to end users to be useful.
This involves clear and consise language, consistent style, useful examples and many other characteristics not tested by CRAN.
Not trivially, it also requires being written in a language the user actually understands.

English is currently the de-facto international language and this is reflected in R function and variable names, like how the `mean()` function is not called `promedio()` or `Mittelwert()` and documentation language.
And while contributed packages have a "Language" field and can be documented in other languages, the vast majority of contributed packages are documented in English.

There is [a small number of packages documented in other languages](https://cderv.rbind.io/2018/03/11/non-english-pkg-in-cran/), presumably in accordance to their target audience.
For example, [labstatR](https://cran.r-project.org/web/packages/labstatR/index.html) is a companion package for the italian book Laboratorio Di Statistica Con R and is documented in Italian.
The [chilemapas](https://cran.r-project.org/web/packages/chilemapas/chilemapas.pdf) package provides various simplified maps for Chile and it's documentation and function names are in Spanish.

Packages documented in non-English languages can be more accessible for their intended populations, but they are much less accessible to the wider community.
Useful functions/algorithms implemented in those packages would be hard to use for the rest of the community.
So package authors are faced with the decision of making their package inaccessible to their target demographic or isolated from the wider ecosystem.

Real cases of this issue exists.
For example, the [utilsIPEA](https://cran.r-project.org/web/packages/utilsIPEA/index.html) package is a package for the Brazilian Instituto de Pesquisa Economica Aplicada is documented in English and it's functions are a mix of English and Portuguese.
The author publicly expressed [his need for bilingual documentation](https://stackoverflow.com/questions/37288823/bilingual-english-and-portuguese-documentation-in-an-r-package):

> I am writing a package to facilitate importing Brazilian socio-economic microdata sets (Census, PNAD, etc).
> I foresee two distinct groups of users of the package:
>
> -   Users in Brazil, who may feel more at ease with the documentation in Portuguese.
>     The probably can understand English to some extent, but a foreign language would probably make the package feel less "ergonomic".
>
> -   The broader international users community, from whom English documentation may be a necessary condition.
>
> Is it possible to write a package in a way that the documentation is "bilingual" (English and Portuguese), and that the language shown to the user will depend on their country/language settings?

Moreover, CRAN hosts at least two packages that have a secondary package version with documentation in another language.
The [ExpDes](https://cran.r-project.org/web/packages/ExpDes/index.html) package has the companion package [ExpDes.pt](https://cran.r-project.org/web/packages/ExpDes.pt/index.html) with documentation in Portuguese.
Similarly, the [orloca](https://cran.r-project.org/web/packages/orloca/index.html) package is documented in Spanish in the [orloca.es](https://cran.r-project.org/web/packages/orloca.es/index.html) package.

Needless to say, this method of bilingual documentation is not recommended, as it's very hard to maintain and doesn't scale to other languages.
A better alternative would be for R to allow packages to have multilingual documentation.
