# The proposal

```{=html}
<!--
This is where the proposal should be outlined. 
-->
```
## Overview

```{=html}
<!--
At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.
-->
```
SDe habló con R core en

We propose to extend the R help system to allow for multiple help pages for the same function in different languages.
By default, `help(function)` would show the documentation in the preferred language of the user or fall-back to the canonical documentation otherwise (most likely, in English).
It would also include a link to the canonical documentation and warnings if translations are out of date.

## Detail

```{=html}
<!--
Go into more detail about the specifics of the project and it delivers against the problem.

Depending on project type the detail section should include:

 - [ ] Minimum Viable Product
 - [ ] Architecture
 - [ ] Assumptions
-->
```
A possible implementation would be as follows:

-   Original packages have their "canonical" help pages written in the original languages.
    (e.g. `mein_paket` is documented in German).

-   Translations are hosted in translation modules that the user can install to get the documentation in that language.
    (e.g. `mein_paket.en` would provide English documentation for `mein_paket`).
    These modules are R packages that use the PackageType field to indicate that they are a translation module (e.g. `PackageType: translation`).
    The Depends field is used to indicate the package being translated and the minimum version supported.

-   Translation modules would store .po files with the translated strings.

-   When a translation module is installed, the .Rd files of the original package are parsed and translated using `gettext()` and the .po files in the translation module and serialised into binary help pages (like regular packages have).

-   When loading a package, R will also search for installed translations and load them too.

-   `help()` gains an new "language" argument which defaults to `Sys.getenv("LANGUAGE")`.

-   `help()` searches for the loaded topics.
    If any translation is available, then it would use the `language` argument to disambiguate.

-   Help pages should include a link to the original (canonical) documentation.

More details can be found in [the rhelpi18n repository](https://github.com/eliocamp/rhelpi18n).

Mapa conceptual
