# Signatories

```{=html}
<!-- 
This section provides the ISC with a view of the support received from the community for a proposal. Acceptance isn't predicated on popularity but community acceptance is important.  Willingness to accept outside input is also a good marker for project delivery. 

An optional section would be for R-Core signatories where changes to R are proposed.
-->
```
## Project team

```{=html}
<!-- 
Who are the people responsible for actually delivering the project if the proposal gets accepted and are already signed up and rearing to go?
-->
```
-   [Elio Campitelli](https://eliocamp.github.io/): Ph.D. student at the University of Buenos Aires in atmospheric sciences and an R package developer.
    They maintain several open-source R packages (e.g., ggnewscale; metR) and contribute to other packages, such as data.table and ggplot2.
    They contributed to the translation of the book R for Data Science to Spanish, and to the translation of rOpenSci materials, including rOpenSci Packages: Development, Maintenance, and Peer Review.

-   Renata Hirota

## Contributors

```{=html}
<!-- 
Who are the people who have actively helped with this proposal but won't necessarily be on the core project team later?
-->
```
-   [Maëlle Salmon](https://masalmon.eu/): research software engineer at rOpenSci, previously in charge of four ISC funded projects (Catalyzing R-hub adoption through R package developer advocacy, HTTP testing in R, R-Ladies organizational guidance, Tooling and Guidance for Translations of Markdown-Based R Content (Quarto, R Markdown)) funded by the ISC, R blogger, volunteer editor for rOpenSci's system of package peer-review.

-   [Yanina Bellini Saibene](https://yabellini.netlify.app/): Community Manager at rOpenSci, R-Ladies Project Lead, Member of The Carpentries Executive Council and RForwards Core Team.
    Co-founder of MetaDocencia, LatinR, and R-Ladies Santa Rosa.
    She lead the collaborative translation of Teaching Teach Together to Spanish and MetaDocencia educational materials to Portuguese.
    She was involved in the translation to Spanish of R for Data Science, R-Ladies's Rules and Guidelines, some lessons by The Carpentries and severals RStudio Cheat Sheets.
    She is leading the Multilingual Publishing project at rOpenSci

-   Michael Chirico?

-   Gergely Daroczi?

-   Hadley?

## Consulted

```{=html}
<!-- 
Who has been given the opportunity to provide feedback on the proposal? This should include any R Consortium & ISC members who the proposal has been discussed with.
-->
```
-   Yanina Bellini Saibene
