# Success

```{=html}
<!-- 
Projects should have a definition of done that is measurable, and a thorough understanding going in of what the risks are to delivery 
-->
```
## Definition of done

```{=html}
<!-- 
What does success look like? 
-->
```
Success of the project will be to have one or more R packages that implement the following functionality:

1.  Parsing .Rd files into .pot files.
2.  Translation of .Rd files using .po files.
3.  Installation of translation modules.
4.  Access of translated documentation using a `help()`-like function.
5.  Modification of rendered help pages to include links to the canonical documentation.

Additionally, toy packages to showcase and test the functionality will be created.

## Measuring success

```{=html}
<!-- 
How will we know when success is achieved, what markers can we use along the way 
-->
```
Use of this functionality in a real world package.

## Future work

```{=html}
<!-- 
How could this be extended / developed in the future by yourself and/or the community in general?
-->
```
Test in real world packages and workflows and gather feedback to improve the system.
Make changes in the help rendered by `help.start()` to support multiple languages.
Once the project is mature, incorporate the functionality into R itself.

## Key risks

```{=html}
<!-- 
What sort of things could come up that can delay or break the project?

 - [ ] People
 - [ ] Processes
 - [ ] Tooling & Technology
 - [ ] Costs

-->
```
.Rd files can be very complex and even dynamically created.
Parsing them could be to hard or brittle to allow for robust creation of .pot files.
Alternatively, the `gettext()` system is designed for short pieces of text and might not prove ergonomical.
In those cases, an alternative system relying on whole .Rd files hosted in translation modules could be explored.
